#!/bin/bash
# Setup script for distributed builds using Icecream
# Run this on BOTH laptops in your build cluster

set -e

echo "=== TeleRynda Distributed Build Setup ==="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

echo -e "${GREEN}Step 1: Installing Icecream...${NC}"
apt update
apt install -y icecc icecc-monitor

# Try to install icemon (optional GUI monitor)
if apt-cache show icemon >/dev/null 2>&1; then
    apt install -y icemon
    echo -e "${GREEN}icemon installed (optional GUI monitor)${NC}"
else
    echo -e "${YELLOW}Note: icemon not available (optional, not required)${NC}"
fi

echo ""
echo -e "${GREEN}Step 2: Detecting network configuration...${NC}"
IP_ADDR=$(ip addr show | grep "inet " | grep -v 127.0.0.1 | head -n1 | awk '{print $2}' | cut -d'/' -f1)
echo "This machine's IP: $IP_ADDR"

echo ""
echo -e "${YELLOW}Step 3: Configuration${NC}"
echo ""
read -p "Is this the SCHEDULER machine (the 'master' that coordinates)? (y/n): " IS_SCHEDULER
read -p "Enter the scheduler IP address (use $IP_ADDR if this is scheduler): " SCHEDULER_IP
read -p "Enter max parallel jobs for this machine (recommended: CPU cores, e.g., 8): " MAX_JOBS

# Create config file
echo "Creating /etc/default/icecream..."
cat > /etc/default/icecream <<EOF
# Icecream configuration for TeleRynda distributed builds
# Generated by setup_distributed_builds.sh

# Network name (must be the same on all machines in the cluster)
ICECC_NETNAME="rynda-build-net"

# Scheduler address
ICECC_SCHEDULER_HOST="$SCHEDULER_IP"

# Number of parallel jobs this machine should run
ICECC_MAX_JOBS="$MAX_JOBS"

# Allow remote jobs (required for distributed builds)
ICECC_ALLOW_REMOTE="yes"

# Optional: Nice level (higher = lower priority, useful if using machine during builds)
# ICECC_NICE_LEVEL="5"

# Log level (info, debug, error)
ICECC_LOG_LEVEL="info"
EOF

echo ""
echo -e "${GREEN}Step 4: Configuring firewall...${NC}"
if command -v ufw &> /dev/null; then
    echo "Detected UFW firewall, opening Icecream ports..."
    ufw allow 8765/tcp  # Scheduler port
    ufw allow 10245/tcp # Daemon port
    ufw status
else
    echo -e "${YELLOW}UFW not detected. If you use a firewall, manually allow ports 8765 and 10245${NC}"
fi

echo ""
echo -e "${GREEN}Step 5: Starting services...${NC}"

if [ "$IS_SCHEDULER" = "y" ] || [ "$IS_SCHEDULER" = "Y" ]; then
    echo "Enabling and starting scheduler service..."
    if [ -f /etc/init.d/icecc-scheduler ]; then
        # Old-style init.d (Debian)
        update-rc.d icecc-scheduler defaults
        /etc/init.d/icecc-scheduler start
    elif systemctl list-unit-files | grep -q icecream-scheduler; then
        # Systemd service
        systemctl enable icecream-scheduler
        systemctl start icecream-scheduler
        systemctl status icecream-scheduler --no-pager
    fi
fi

echo "Enabling and starting daemon service..."
if [ -f /etc/init.d/iceccd ]; then
    # Old-style init.d (Debian)
    update-rc.d iceccd defaults
    /etc/init.d/iceccd start
    /etc/init.d/iceccd status || echo "Daemon started"
elif systemctl list-unit-files | grep -q icecream.service; then
    # Systemd service
    systemctl enable icecream
    systemctl start icecream
    systemctl status icecream --no-pager
fi

echo ""
echo -e "${GREEN}Step 6: Verifying installation...${NC}"
sleep 2
echo "Checking cluster status..."
icecc -s || echo -e "${YELLOW}Note: Status may be empty if other machines aren't set up yet${NC}"

echo ""
echo -e "${GREEN}=== Setup Complete! ===${NC}"
echo ""
echo "Next steps:"
echo "1. Run this script on your OTHER laptop(s) with the same SCHEDULER_IP"
echo "2. On your development machine, enable Icecream in cmake_local_user.cmake:"
echo "   Uncomment: find_program(ICECC_PROGRAM icecc)"
echo "3. Reconfigure and rebuild:"
echo "   cd /home/denis/develop/me/rynda/build/Desktop_Qt_6_10_0-Release"
echo "   cmake .."
echo "   cmake --build . -j32"
echo ""
echo "Monitor builds with: icemon   (GUI)"
echo "Or:                  watch icecc -s   (terminal)"
echo ""
echo "For more info, see: docs/distributed-builds.md"



